# DAY-4
    -more Functional Programming
        -Comprehensions
        -Generators expressions
        -Decorators
    -Data Analytics
        -numpy
        -pandas
        -visualization/plotting : matplotlib, seaborn
    -Machine Learning
        -statistics (numpy, scipy)
        -Scikit learn (sklearn)
        -Classification
        -Regression
        -Clustering

In [1]:
items  = ['bread',  'butter',  'cookies',  'jam', 'chips', 'soda']
prices = [55,       125.5,      45.55,     190,    35.50,   75]
counts = [2,        1,          8,         1,      10,      4]

In [2]:
# total bill amount
def ind_price(price, count):
    return price*count

bills = list(map(ind_price, prices, counts ))
sum(bills)

1444.9

In [3]:
sum([price*count  for price,count in zip(prices,counts)])

1444.9

In [4]:
def square(num):
    return num**2

nums = range(20,30)
sum(map(square, nums))

6085

In [5]:
sum([num**2 for num in nums])

6085

    -Comprhension : faster
    -map : memory-efficient
    -Comprhension : memory heavy
    -Comprhension : easier for expression
    -Generator : easier for expression but not memory heavy

In [6]:
[num**2 for num in nums] #list comprhension

[400, 441, 484, 529, 576, 625, 676, 729, 784, 841]

In [7]:
(num**2 for num in nums)  #generator expressions return generator object

<generator object <genexpr> at 0x000001E4C54C3370>

In [8]:
list(num**2 for num in nums)

[400, 441, 484, 529, 576, 625, 676, 729, 784, 841]

In [9]:
sum((num**2 for num in nums))
sum(num**2 for num in nums) # allowed to use single bracket also

6085

In [10]:
{ item:price for item, price in zip(items,prices) } #dictionary comprhension

{'bread': 55,
 'butter': 125.5,
 'cookies': 45.55,
 'jam': 190,
 'chips': 35.5,
 'soda': 75}

In [11]:
{num**2 for num in nums}  # set comphrensions

{400, 441, 484, 529, 576, 625, 676, 729, 784, 841}

In [12]:
(num**2 for num in nums) 

<generator object <genexpr> at 0x000001E4C55413C0>

# Data Analytics

In [16]:
i = 10 #4 bytes
f = 4.2 #4 bytes
nums = [1,2,3,4] #16 Bytes

In [14]:
import os, sys

In [17]:
sys.getsizeof(i)

28

In [19]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [22]:
type(arr)

numpy.ndarray

In [23]:
len(arr)

4

In [24]:
arr[:2]

array([1, 2])

In [25]:
arr.size

4

In [26]:
farr = np.array([1.1,2.2,3.3])
farr

array([1.1, 2.2, 3.3])

In [27]:
arr.dtype

dtype('int32')

In [28]:
farr.dtype

dtype('float64')

In [31]:
farr = np.array([1.1,2.2,3.3], dtype = np.float16)
farr

array([1.1, 2.2, 3.3], dtype=float16)

In [33]:
farr.dtype

dtype('float16')

In [36]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
len(arr2d)

3

In [38]:
arr2d.size

9

In [39]:
arr2d.shape

(3, 3)

In [41]:
arr2d[-1]

array([7, 8, 9])

In [42]:
arr2d[-1][-1]

9

In [45]:
arr2d[0,1]

2

In [49]:
arr2d[0:2,:2]

array([[1, 2],
       [4, 5]])

In [51]:
np.array(1).ndim #scalar

0

In [52]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr2 = np.arange(6,7,0.1)
arr2

array([6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9])

In [55]:
arr1 + arr2

array([ 6. ,  7.1,  8.2,  9.3, 10.4, 11.5, 12.6, 13.7, 14.8, 15.9])

In [56]:
arr1 * arr2

array([ 0. ,  6.1, 12.4, 18.9, 25.6, 32.5, 39.6, 46.9, 54.4, 62.1])

In [57]:
arr1.shape

(10,)

In [58]:
arr1+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
arr1[arr1>arr2]

array([7, 8, 9])

In [63]:
nums = np.random.random(10)
nums

array([0.58292634, 0.86908881, 0.78104767, 0.23697094, 0.73307019,
       0.23957877, 0.63572269, 0.45950308, 0.82743062, 0.78503794])

In [64]:
nums[nums<100]

array([0.58292634, 0.86908881, 0.78104767, 0.23697094, 0.73307019,
       0.23957877, 0.63572269, 0.45950308, 0.82743062, 0.78503794])

In [65]:
nums+9

array([9.58292634, 9.86908881, 9.78104767, 9.23697094, 9.73307019,
       9.23957877, 9.63572269, 9.45950308, 9.82743062, 9.78503794])

In [66]:
nums*90+10

array([62.46337018, 88.21799304, 80.29429008, 31.32738482, 75.97631678,
       31.5620897 , 67.21504169, 51.35527718, 84.46875603, 80.6534144 ])

# Pandas : 2D labelled data


In [67]:
import pandas as pd

In [70]:
tips=pd.read_csv('tips.csv')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [71]:
type(tips)

pandas.core.frame.DataFrame

In [72]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [73]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [74]:
len(tips)

244

In [75]:
tips.shape

(244, 7)

In [76]:
tips.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [77]:
tips['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [78]:
type(tips['tip'])

pandas.core.series.Series

In [79]:
tips['tip']+10

0      11.01
1      11.66
2      13.50
3      13.31
4      13.61
       ...  
239    15.92
240    12.00
241    12.00
242    11.75
243    13.00
Name: tip, Length: 244, dtype: float64

In [80]:
sum(tips['tip'])

731.58

In [81]:
tips['total_bill'] - tips['tip']

0      15.98
1       8.68
2      17.51
3      20.37
4      20.98
       ...  
239    23.11
240    25.18
241    20.67
242    16.07
243    15.78
Length: 244, dtype: float64

In [82]:
tip = tips['tip']
tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [83]:
tip>2.5

0      False
1      False
2       True
3       True
4       True
       ...  
239     True
240    False
241    False
242    False
243     True
Name: tip, Length: 244, dtype: bool

In [84]:
tip[tip > 2.5]

2      3.50
3      3.31
4      3.61
5      4.71
7      3.12
       ... 
232    3.39
234    3.00
238    4.67
239    5.92
243    3.00
Name: tip, Length: 136, dtype: float64

In [85]:
tips[tip>2.5]

total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
232       11.61  3.39    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[136 rows x 7 columns]

In [87]:
tips[tip>2.5]['total_bill'].mean()

23.78345588235294

In [90]:
tips[tips['sex']=='Female']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [92]:
tips[tips['sex']=='Female']['tip'].mean()

2.8334482758620685

In [93]:
tips[tips['day']=='Sun']['tip'].sum()

247.39000000000001

In [94]:
round(tips[tips['day']=='Sun']['tip'].sum(),2)

247.39

#  To Avoid - Floation point errors
    -use decimal Decimal

In [95]:
import decimal # to avoid decimal point errors

In [97]:
decimal.Decimal('2.3001')

Decimal('2.3001')

In [107]:
tips[(tips['smoker'] == 'Yes') & (tips['sex']=='Male')]['total_bill'].mean()

22.284499999999998

In [111]:
#average total_bill paid by male smoker on sunday dinners

#filters
males = tips['sex']=='Male'
smokers = tips['smoker']=='Yes'
sun = tips['day'] == 'Sun'
dinner = tips['time'] == 'Dinner'

tips[males & smokers & sun & dinner]['total_bill'].mean()

26.14133333333334

In [112]:
tips.groupby('day')

In [113]:
tips['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [115]:
tips.groupby('day')['total_bill'].mean()

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64